Repository listendev/lstn, pull requests merged in 2023-03, with the labels that each got.

#117 feat: create bash install script
  install.sh
Labels: enhancement, large, needs-review

#122 feat(pkg/validation): make the npm package name lax by default
  pkg/validate/npm_package_name.go
Labels: enhancement, needs-review, small

#131 ci: lint shell scripts
  .gitattributes
  .github/workflows/cla.yml
  .github/workflows/lint.yml
  .github/workflows/shellcheck.yml
Labels: ci, needs-review, small

#142 feat!: make the scan child command the new default one
  cmd/root/root.go
Labels: enhancement, needs-review, small, breaking-change

#147 ci: switch to setup-go@v4 with automatic cache management
  .github/workflows/build.yml
  .github/workflows/lint.yml
  .github/workflows/release.yml
  .github/workflows/tests.yml
Labels: ci, needs-review, small

#161 chore: golangci-lint format print affected file
  .github/workflows/lint.yml
Labels: ci, needs-review, small, no-releasenotes

#180 chore(pkg/cmd/report/templates): address style changes in #177
  pkg/cmd/report/templates/container.go
  pkg/cmd/report/templates/single_verdicts.go
Labels: needs-review, small, no-releasenotes

#156 ci: use common reviewpad file
  reviewpad.yml
Labels: ci, small

#208 fix: make `lstn to --debug-options` work
  cmd/commands_test.go
  cmd/to/to.go
Labels: bug, needs-review, small
